'use client'
import { useState } from 'react'
type Action = 'give_item'|'remove_item'|'give_money'|'remove_money'|'kick'|'ban'|'console'
export default function Panel() {
  const [action, setAction] = useState<Action>('give_item'); const [target, setTarget] = useState(''); const [item, setItem] = useState(''); const [amount, setAmount] = useState('1'); const [reason, setReason] = useState(''); const [notice, setNotice] = useState('')
  async function send(e: React.FormEvent) { e.preventDefault(); setNotice('جارٍ الإرسال…'); const payload:any={ target:Number(target), item, amount:Number(amount), reason }; if(action==='console') payload.command=reason; const r=await fetch('/api/commands',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})}); setNotice(r.ok?'تمت إضافة الأمر إلى قائمة التنفيذ':'تعذر إرسال الأمر') }
  const needsItem=['give_item','remove_item'].includes(action), needsAmount=['give_item','remove_item','give_money','remove_money'].includes(action)
  return <main className="panel"><header><div><span className="tag">PRIVATE</span><h1>QBCore Control</h1></div><a href="/api/logout">تسجيل الخروج</a></header><section className="hero"><h2>إدارة FiveM من مكان واحد</h2><p>كل عملية تُسجل وتُنفذ عبر مورد السيرفر الآمن.</p></section><form className="card" onSubmit={send}><label>الإجراء<select value={action} onChange={e=>setAction(e.target.value as Action)}><option value="give_item">إعطاء Item</option><option value="remove_item">سحب Item</option><option value="give_money">إعطاء فلوس</option><option value="remove_money">سحب فلوس</option><option value="kick">Kick لاعب</option><option value="ban">Ban عبر txAdmin</option><option value="console">أمر Console</option></select></label>{action!=='console'&&<label>Server ID اللاعب<input required inputMode="numeric" value={target} onChange={e=>setTarget(e.target.value)} placeholder="مثال: 12"/></label>}{needsItem&&<label>اسم الـItem<input required value={item} onChange={e=>setItem(e.target.value)} placeholder="bread"/></label>}{needsAmount&&<label>الكمية<input required min="1" type="number" value={amount} onChange={e=>setAmount(e.target.value)} /></label>}<label>{action==='console'?'الأمر (للمالك فقط)':action==='ban'||action==='kick'?'السبب':'ملاحظة'}<input value={reason} onChange={e=>setReason(e.target.value)} placeholder={action==='console'?'ensure resource_name':'اختياري'} required={action==='console'} /></label><button>تنفيذ</button>{notice&&<p className="notice">{notice}</p>}</form><aside><strong>مهم:</strong> تشغيل وإيقاف FXServer بالكامل يحتاج Windows Agent إضافيًا. المورد الحالي يدير الأوامر داخل السيرفر فقط.</aside></main>
}
